[package]
name = "my-password-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "genpass"
path = "src/main.rs"

[dependencies]
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
